blank_issues_enabled: false
contact_links:
  - name: Generally curious?
    url: https://github.com/organizations/AutoIt-Community
    about: Feel free to explore the AutoIt-Community organization on GitHub.
  - name: Who's Sven?
    url: https://github.com/sven-seyfert
    about: Feel free to explore my profile and repositories on GitHub.
